import type { AnalyticsEventName } from "@/lib/analytics/types";

export const ANALYTICS_EVENTS = {
  pageView: "page_view",
  gameImpression: "game_impression",
  gameClick: "game_click",
  gameStart: "game_start",
  gameViewed: "game_viewed",
  gamePlayClicked: "game_play_clicked",
  gameStarted: "game_started",
  gameExit: "game_exit",
  search: "search",
  authLoginViewed: "auth_login_viewed",
  authLoginSubmitted: "auth_login_submitted",
  authLoginSucceeded: "auth_login_succeeded",
  authLoginFailed: "auth_login_failed",
  authRegisterSubmitted: "auth_register_submitted",
  authRegisterSucceeded: "auth_register_succeeded",
  authRegisterFailed: "auth_register_failed",
  authLogout: "auth_logout",
  myGamesViewed: "my_games_viewed",
  favoritesViewed: "favorites_viewed",
  historyViewed: "history_viewed",
  favoriteAdded: "favorite_added",
  favoriteRemoved: "favorite_removed",
  historyGameClicked: "history_game_clicked",
  myGamesGameClicked: "my_games_game_clicked",
  communityViewed: "community_viewed",
  communityPostCreated: "community_post_created",
  communityPostViewed: "community_post_viewed",
  communityCommentCreated: "community_comment_created",
  communityReactionAdded: "community_reaction_added",
  communityReviewCreated: "community_review_created",
  communityUserFollowed: "community_user_followed",
  communityLeaderboardViewed: "community_leaderboard_viewed",
  communityReportCreated: "community_report_created",
} as const satisfies Record<string, AnalyticsEventName>;
