export type AnalyticsEventName =
  | "page_view"
  | "game_impression"
  | "game_click"
  | "game_start"
  | "game_viewed"
  | "game_play_clicked"
  | "game_started"
  | "game_exit"
  | "search"
  | "auth_login_viewed"
  | "auth_login_submitted"
  | "auth_login_succeeded"
  | "auth_login_failed"
  | "auth_register_submitted"
  | "auth_register_succeeded"
  | "auth_register_failed"
  | "auth_logout"
  | "my_games_viewed"
  | "favorites_viewed"
  | "history_viewed"
  | "favorite_added"
  | "favorite_removed"
  | "history_game_clicked"
  | "my_games_game_clicked";

export type AnalyticsPayload = Record<string, string | number | boolean | null | undefined>;
